export default [
  "Evtx",
  "Registry",
  "LNK",
  "JumpList",
  "ShellBag",
  "UserAssist",
  "Prefetch",
  "ShimCache",
  "AmCache",
  "MUICache",
  "SRUM",
  "Windows Timeline",
  "ThumbCache",
  "Recycle.bin",
  "Windows.edb",
  "File System",
  "WER",
  "Windows 복구 및 초기화",
  "TaskScheduler",
  "문서 및 멀티미디어",
  "Web Artifact",
  "OST/PST",
  "OneDrive",
  "Windows 기본 앱",
  "Slack",
  "Discord",
  "Notion",
  "Kakao",
  "Google Drive",
  "Facebook Messenger",
  "Keyword Search",
  "항목 없음",
  "모름",
];
